### PR TITLE
Change Settings to About

### PR DESCRIPTION
**Pull request by dirkcuys**
These changes relate to #69, #70, #71 & #72

@kimdhamilton I'm not sure if this is ready to merge. I've updated it so that a new About screen will be used instead of the Settings screen, but there still a lot I'm learning about react-native, typescript and how the application is structured.

I also haven't styled the text and and the icon was just a quick placeholder, I'm not sure what the guidelines are around these?

This PR includes the changes from the previous PR: #75

### CODE REVIEW

**Review by kimdhamilton — APPROVED** [review]
LGTM; feel free to merge when ready

**Comment by kimdhamilton** [comment]
@dirkcuys -- I'm sorry; somehow there was a miscommunication and this commit was merged https://github.com/digitalcredentials/cred-wallet/commit/09655fbf47e175c9ed4adefc3ce8c073a9e5ece0, which is attempting to do the same thing but has some issues (I'll comment on that merged PR). 

I'll try to make sure that doesn't happen going forward.

**Comment by dirkcuys** [comment]
@kimdhamilton no worries, let me know if I should resolve the conflicts or if I should just transfer the changes to the already merge code? It looks like the main difference is that the other update preserves the navigation stack for settings?

**Comment by kimdhamilton** [comment]
Yes, please resolve the conflicts -- your original changes were perfect, but I'm not 100% sure how to resolve them.

**Comment by dirkcuys** [comment]
@kimdhamilton I resolved the conflicts - this PR will replace the "Settings" navigation stack with a single "About" page. That will also effectively remove access to the Backup screen.

**Pull request merged**
